#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _Cav12_reg(void);
extern void _Cav13_reg(void);
extern void _Cav2_3_reg(void);
extern void _Cav3_1_reg(void);
extern void _GOLGI_Ampa_mossy_det_vi_reg(void);
extern void _GOLGI_Ampa_pf_aa_det_vi_reg(void);
extern void _GRANULE_Ampa_det_vi_reg(void);
extern void _GRANULE_Nmda_det_vi_reg(void);
extern void _GRC_CA_reg(void);
extern void _GRC_KM_reg(void);
extern void _GRC_NA_reg(void);
extern void _GRC_NA_FHF_reg(void);
extern void _Hcn1_reg(void);
extern void _Hcn2_reg(void);
extern void _Kca11_reg(void);
extern void _Kca22_reg(void);
extern void _Kca31_reg(void);
extern void _Kir23_reg(void);
extern void _Kv11_reg(void);
extern void _Kv15_reg(void);
extern void _Kv22_reg(void);
extern void _Kv34_reg(void);
extern void _Kv43_reg(void);
extern void _Leak_reg(void);
extern void _Nav16_reg(void);
extern void _PC_NMDA_NR2B_reg(void);
extern void _UBC_TRP_reg(void);
extern void _cdp5StCmod_reg(void);
extern void _cdp5_CR_reg(void);
extern void _cdp5_CR_CAM_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"Cav12.mod\"");
    fprintf(stderr," \"Cav13.mod\"");
    fprintf(stderr," \"Cav2_3.mod\"");
    fprintf(stderr," \"Cav3_1.mod\"");
    fprintf(stderr," \"GOLGI_Ampa_mossy_det_vi.mod\"");
    fprintf(stderr," \"GOLGI_Ampa_pf_aa_det_vi.mod\"");
    fprintf(stderr," \"GRANULE_Ampa_det_vi.mod\"");
    fprintf(stderr," \"GRANULE_Nmda_det_vi.mod\"");
    fprintf(stderr," \"GRC_CA.mod\"");
    fprintf(stderr," \"GRC_KM.mod\"");
    fprintf(stderr," \"GRC_NA.mod\"");
    fprintf(stderr," \"GRC_NA_FHF.mod\"");
    fprintf(stderr," \"Hcn1.mod\"");
    fprintf(stderr," \"Hcn2.mod\"");
    fprintf(stderr," \"Kca11.mod\"");
    fprintf(stderr," \"Kca22.mod\"");
    fprintf(stderr," \"Kca31.mod\"");
    fprintf(stderr," \"Kir23.mod\"");
    fprintf(stderr," \"Kv11.mod\"");
    fprintf(stderr," \"Kv15.mod\"");
    fprintf(stderr," \"Kv22.mod\"");
    fprintf(stderr," \"Kv34.mod\"");
    fprintf(stderr," \"Kv43.mod\"");
    fprintf(stderr," \"Leak.mod\"");
    fprintf(stderr," \"Nav16.mod\"");
    fprintf(stderr," \"PC_NMDA_NR2B.mod\"");
    fprintf(stderr," \"UBC_TRP.mod\"");
    fprintf(stderr," \"cdp5StCmod.mod\"");
    fprintf(stderr," \"cdp5_CR.mod\"");
    fprintf(stderr," \"cdp5_CR_CAM.mod\"");
    fprintf(stderr, "\n");
  }
  _Cav12_reg();
  _Cav13_reg();
  _Cav2_3_reg();
  _Cav3_1_reg();
  _GOLGI_Ampa_mossy_det_vi_reg();
  _GOLGI_Ampa_pf_aa_det_vi_reg();
  _GRANULE_Ampa_det_vi_reg();
  _GRANULE_Nmda_det_vi_reg();
  _GRC_CA_reg();
  _GRC_KM_reg();
  _GRC_NA_reg();
  _GRC_NA_FHF_reg();
  _Hcn1_reg();
  _Hcn2_reg();
  _Kca11_reg();
  _Kca22_reg();
  _Kca31_reg();
  _Kir23_reg();
  _Kv11_reg();
  _Kv15_reg();
  _Kv22_reg();
  _Kv34_reg();
  _Kv43_reg();
  _Leak_reg();
  _Nav16_reg();
  _PC_NMDA_NR2B_reg();
  _UBC_TRP_reg();
  _cdp5StCmod_reg();
  _cdp5_CR_reg();
  _cdp5_CR_CAM_reg();
}
